version: '3.8'
services:
  go_local:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
      target: dev
    container_name: 'go_local'
    working_dir: '/go/'
    tty: true
    volumes:
      - ./project/src:/go/src
      - ./docker/local/credentials:/go/credentials
      - ./openapi:/go/src/openapi
    ports:
      - 3000:8080
      - 3001:3001
    networks:
      shared-network:
        ipv4_address: 172.30.0.2
    env_file:
      - ./env/common.env
      - ./env/local.env
      - ./env/secret_keys.env
    command: >
      bash -c '
        /bin/bash
      '
  firebase_emulator:
    build:
      context: .
      dockerfile: ./docker/local/firebase/Dockerfile
    container_name: 'firebase_emulator'
    volumes:
      - ./docker/local/firebase/.firebaserc:/opt/firebase/.firebaserc
      # - ./docker/local/firebase/firebase-debug.log:/opt/firebase/firebase-debug.log
      - ./docker/local/firebase/firebase.json:/opt/firebase/firebase.json
      - ./docker/local/firebase/firestore.indexes.json:/opt/firebase/firestore.indexes.json
      - ./docker/local/firebase/firestore.rules:/opt/firebase/firestore.rules
      - ./docker/local/firebase/storage.rules:/opt/firebase/storage.rules
      - ./docker/local/firebase/bin/:/root/.cache:cached
      - ./docker/local/firebase/config/:/root/.config:cached
      - ./docker/local/firebase/data:/opt/firebase/data
    ports:
      - 9099:9099 # Firebase Authentication
      - 5001:5001 # Clound Functions
      - 8080:8080 # Cloud Firestore
      - 9000:9000 # Realtime Database
      - 5050:5050 # Firebase Hosting
      - 8085:8085 # Cloud Pub/Sub
      - 9199:9199 # Cloud Storage
      - 4000:4000 # Emulator Suite UI
    working_dir: /opt/firebase
    networks:
      shared-network:
        ipv4_address: 172.30.0.3
    command: firebase emulators:start --import=/opt/firebase/data/persistence --export-on-exit
    tty: true

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8002:8080"
    volumes:
      - ./openapi:/openapi
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml

networks:
  shared-network:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 172.30.0.0/24
