/*
Spot

A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package entity

import (
	"encoding/json"
)

// checks if the Instagram type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Instagram{}

// Instagram struct for Instagram
type Instagram struct {
	Types []string `json:"types,omitempty" firestore:"types"`
	Reviews []Review `json:"reviews,omitempty" firestore:"reviews"`
	Rating *float64 `json:"rating,omitempty" firestore:"rating"`
	Photos []Photo `json:"photos,omitempty" firestore:"photos"`
}

// NewInstagram instantiates a new Instagram object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInstagram() *Instagram {
	this := Instagram{}
	return &this
}

// NewInstagramWithDefaults instantiates a new Instagram object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInstagramWithDefaults() *Instagram {
	this := Instagram{}
	return &this
}

// GetTypes returns the Types field value if set, zero value otherwise.
func (o *Instagram) GetTypes() []string {
	if o == nil || IsNil(o.Types) {
		var ret []string
		return ret
	}
	return o.Types
}

// GetTypesOk returns a tuple with the Types field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instagram) GetTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.Types) {
		return nil, false
	}
	return o.Types, true
}

// HasTypes returns a boolean if a field has been set.
func (o *Instagram) HasTypes() bool {
	if o != nil && !IsNil(o.Types) {
		return true
	}

	return false
}

// SetTypes gets a reference to the given []string and assigns it to the Types field.
func (o *Instagram) SetTypes(v []string) {
	o.Types = v
}

// GetReviews returns the Reviews field value if set, zero value otherwise.
func (o *Instagram) GetReviews() []Review {
	if o == nil || IsNil(o.Reviews) {
		var ret []Review
		return ret
	}
	return o.Reviews
}

// GetReviewsOk returns a tuple with the Reviews field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instagram) GetReviewsOk() ([]Review, bool) {
	if o == nil || IsNil(o.Reviews) {
		return nil, false
	}
	return o.Reviews, true
}

// HasReviews returns a boolean if a field has been set.
func (o *Instagram) HasReviews() bool {
	if o != nil && !IsNil(o.Reviews) {
		return true
	}

	return false
}

// SetReviews gets a reference to the given []Review and assigns it to the Reviews field.
func (o *Instagram) SetReviews(v []Review) {
	o.Reviews = v
}

// GetRating returns the Rating field value if set, zero value otherwise.
func (o *Instagram) GetRating() float64 {
	if o == nil || IsNil(o.Rating) {
		var ret float64
		return ret
	}
	return *o.Rating
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instagram) GetRatingOk() (*float64, bool) {
	if o == nil || IsNil(o.Rating) {
		return nil, false
	}
	return o.Rating, true
}

// HasRating returns a boolean if a field has been set.
func (o *Instagram) HasRating() bool {
	if o != nil && !IsNil(o.Rating) {
		return true
	}

	return false
}

// SetRating gets a reference to the given float64 and assigns it to the Rating field.
func (o *Instagram) SetRating(v float64) {
	o.Rating = &v
}

// GetPhotos returns the Photos field value if set, zero value otherwise.
func (o *Instagram) GetPhotos() []Photo {
	if o == nil || IsNil(o.Photos) {
		var ret []Photo
		return ret
	}
	return o.Photos
}

// GetPhotosOk returns a tuple with the Photos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Instagram) GetPhotosOk() ([]Photo, bool) {
	if o == nil || IsNil(o.Photos) {
		return nil, false
	}
	return o.Photos, true
}

// HasPhotos returns a boolean if a field has been set.
func (o *Instagram) HasPhotos() bool {
	if o != nil && !IsNil(o.Photos) {
		return true
	}

	return false
}

// SetPhotos gets a reference to the given []Photo and assigns it to the Photos field.
func (o *Instagram) SetPhotos(v []Photo) {
	o.Photos = v
}

func (o Instagram) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Instagram) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Types) {
		toSerialize["types"] = o.Types
	}
	if !IsNil(o.Reviews) {
		toSerialize["reviews"] = o.Reviews
	}
	if !IsNil(o.Rating) {
		toSerialize["rating"] = o.Rating
	}
	if !IsNil(o.Photos) {
		toSerialize["photos"] = o.Photos
	}
	return toSerialize, nil
}

type NullableInstagram struct {
	value *Instagram
	isSet bool
}

func (v NullableInstagram) Get() *Instagram {
	return v.value
}

func (v *NullableInstagram) Set(val *Instagram) {
	v.value = val
	v.isSet = true
}

func (v NullableInstagram) IsSet() bool {
	return v.isSet
}

func (v *NullableInstagram) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInstagram(val *Instagram) *NullableInstagram {
	return &NullableInstagram{value: val, isSet: true}
}

func (v NullableInstagram) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInstagram) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


