/*
 * Spot
 *
 * A sample API that uses a petstore as an example to demonstrate features in the OpenAPI 3.0 specification
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
)



// DefaultApiRouter defines the required methods for binding the api requests to a responses for the DefaultApi
// The DefaultApiRouter implementation should parse necessary information from the http request,
// pass the data to a DefaultApiServicer to perform the required actions, then write the service results to the http response.
type DefaultApiRouter interface { 
	HealthcheckGet(http.ResponseWriter, *http.Request)
	RootGet(http.ResponseWriter, *http.Request)
	V1SpotsGet(http.ResponseWriter, *http.Request)
	V1SpotsIdGet(http.ResponseWriter, *http.Request)
}


// DefaultApiServicer defines the api actions for the DefaultApi service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type DefaultApiServicer interface { 
	HealthcheckGet(context.Context) (ImplResponse, error)
	RootGet(context.Context) (ImplResponse, error)
	V1SpotsGet(context.Context, string) (ImplResponse, error)
	V1SpotsIdGet(context.Context, string) (ImplResponse, error)
}
